// Get all users
GET http://localhost:5000/api/users

###
// Create a new user
POST http://localhost:5000/api/users
Content-Type: application/json

{
    "name": "Tae Kweon",
    "email": "taekweon@gmail.com"
}

###

GET http://localhost:5000/api/auth

###

GET http://localhost:5000/api/workouts