// Get all users
GET http://localhost:5000/api/users

###
// Create a new user
POST http://localhost:5000/api/users
Content-Type: application/json

{
    "name": "Tae Kweon",
    "email": "taekweon@gmail.com"
}

###

GET http://localhost:5000/api/auth

###
// Get all workouts
GET http://localhost:5000/api/workouts

###
// Create a workout
POST http://localhost:5000/api/workouts
Content-Type: application/json

{
    "name": "The Best Workout 2000",
    "date": "06-08-2021"

}

###

DELETE http://localhost:5000/api/workouts/60c3b61db3667015780ee90f

###